/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unilab.unicafe.view;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author jefponte
 */
public class FrameClientDesbloqueio extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form FrameClientDesbloqueio
	 */
	public FrameClientDesbloqueio() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		fieldTempo = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		fieldUsuario = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		fieldHoraEntrada = new javax.swing.JTextField();
		btnEncerrar = new javax.swing.JButton();
		btnEncerrar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				
				System.out.println("Apertou");
			}
		});
		jLabel4 = new javax.swing.JLabel();
		fieldTempo1 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
		setUndecorated(true);
		setResizable(false);

		fieldTempo.setEditable(false);
		fieldTempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		fieldTempo.setText("30:00");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Tempo Restante: ");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Usuario: ");

		fieldUsuario.setEditable(false);
		fieldUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		fieldUsuario.setText("Jefponte");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Hora de Entrada: ");

		fieldHoraEntrada.setEditable(false);
		fieldHoraEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		fieldHoraEntrada.setText("17:32");

		btnEncerrar.setText("Encerrar Sessao");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("Status Conexao:");

		fieldTempo1.setEditable(false);
		fieldTempo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		fieldTempo1.setText("Ok");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel3)
					.addGap(18)
					.addComponent(fieldHoraEntrada)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(jLabel2)
					.addGap(18)
					.addComponent(fieldUsuario, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(jLabel1)
					.addGap(18)
					.addComponent(fieldTempo, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
					.addGap(63)
					.addComponent(jLabel4)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(fieldTempo1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
					.addComponent(btnEncerrar)
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(9)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(fieldHoraEntrada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2)
								.addComponent(fieldUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1)
								.addComponent(fieldTempo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEncerrar)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(fieldTempo1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
					.addContainerGap(41, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 972, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(100, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(100, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public JButton getBtnEncerrar() {

		return this.btnEncerrar;

	}

	public JTextField getFieldTempo() {
		return this.fieldTempo;
	}

	public JTextField getFieldHoraEntrada() {
		return this.fieldHoraEntrada;
	}

	public JTextField getFieldUsuario() {

		return this.fieldUsuario;

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnEncerrar;
	private javax.swing.JTextField fieldHoraEntrada;
	private javax.swing.JTextField fieldTempo;
	private javax.swing.JTextField fieldTempo1;
	private javax.swing.JTextField fieldUsuario;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}
